spring.application.name=pocket-ai-scribe

spring.config.import=optional:file:.env[.properties]

sber.auth.key=${SBER_AUTH_KEY:}
sber.speech.url=${SBER_SPEECH_URL:https://smartspeech.sber.ru/rest/v1/speech:recognize}
sber.speech.scope=${SBER_SPEECH_SCOPE:SALUTE_SPEECH_PERS}
server.address=0.0.0.0
obsidian.inbox.path=path
